apiVersion: ayb.dcas.dev/v1
kind: Build
metadata:
  name: workstation:base
spec:
  from: ${BASE:-python:3.13-slim}
  user:
    uid: 1000
    shell: /bin/bash
    username: somebody
  repositories:
    debian:
      - url: ${DEBIAN_REGISTRY_MIRROR:-http://deb.debian.org/debian} trixie main
      - url: ${DEBIAN_REGISTRY_MIRROR:-http://deb.debian.org/debian} trixie-updates main
  packages:
    - type: Debian
      names:
        - bash
        - openssh-server
        - openssh-client
        - curl
        - gnupg
        - libstdc++6
        - gcc
        - util-linux
        - build-essential
        - git
        - vim
        - jq
        - ca-certificates
        - gzip
        - tar
        - code-server
  entrypoint:
    - /bin/bash