services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks: [monitoring]

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks: [monitoring]

networks:
  monitoring:
    external: true
    
